local M = {}
function M.setup(c, opts)
  return {
    BlinkCmpMenu = { fg = c.fg, bg = c.bg_float },
    BlinkCmpMenuBorder = { fg = c.surface2, bg = c.bg_float },
    BlinkCmpMenuSelection = { fg = c.fg, bg = c.bg_visual },
    BlinkCmpScrollBarThumb = { bg = c.surface2 },
    BlinkCmpScrollBarGutter = { bg = c.surface0 },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.fg_muted, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.iris, bold = true },
    BlinkCmpKind = { fg = c.fg_dim },
    BlinkCmpKindClass = { fg = c.blue },
    BlinkCmpKindConstant = { fg = c.teal },
    BlinkCmpKindConstructor = { fg = c.iris },
    BlinkCmpKindEnum = { fg = c.blue },
    BlinkCmpKindEnumMember = { fg = c.teal },
    BlinkCmpKindEvent = { fg = c.rose },
    BlinkCmpKindField = { fg = c.fg },
    BlinkCmpKindFile = { fg = c.fg_dim },
    BlinkCmpKindFolder = { fg = c.gold },
    BlinkCmpKindFunction = { fg = c.fg },
    BlinkCmpKindInterface = { fg = c.blue },
    BlinkCmpKindKeyword = { fg = c.fg_dim },
    BlinkCmpKindMethod = { fg = c.fg },
    BlinkCmpKindModule = { fg = c.fg_dim },
    BlinkCmpKindOperator = { fg = c.fg_dim },
    BlinkCmpKindProperty = { fg = c.fg },
    BlinkCmpKindReference = { fg = c.link },
    BlinkCmpKindSnippet = { fg = c.gold },
    BlinkCmpKindStruct = { fg = c.blue },
    BlinkCmpKindText = { fg = c.fg },
    BlinkCmpKindTypeParameter = { fg = c.blue },
    BlinkCmpKindUnit = { fg = c.teal },
    BlinkCmpKindValue = { fg = c.teal },
    BlinkCmpKindVariable = { fg = c.fg },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg_float },
    BlinkCmpDocBorder = { fg = c.surface2, bg = c.bg_float },
    BlinkCmpDocSeparator = { fg = c.surface2, bg = c.bg_float },
    BlinkCmpDocCursorLine = { bg = c.bg_cursorline },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_float },
    BlinkCmpSignatureHelpBorder = { fg = c.surface2, bg = c.bg_float },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.none, bg = c.gold_bg, bold = true },
  }
end
return M
