local M = {}
function M.setup(c, opts)
  return {
    BufferLineBackground = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineBuffer = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg_dim, bg = c.bg_alt },
    BufferLineDuplicate = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineDuplicateSelected = { fg = c.fg_dim, bg = c.bg, italic = true },
    BufferLineDuplicateVisible = { fg = c.fg_muted, bg = c.bg_alt, italic = true },
    BufferLineFill = { fg = c.fg_muted, bg = c.surface1 },
    BufferLineIndicatorSelected = { fg = c.blue, bg = c.bg },
    BufferLineIndicatorVisible = { fg = c.bg_alt, bg = c.bg_alt },
    BufferLineModified = { fg = c.warn, bg = c.surface0 },
    BufferLineModifiedSelected = { fg = c.warn, bg = c.bg },
    BufferLineModifiedVisible = { fg = c.warn, bg = c.bg_alt },
    BufferLineSeparator = { fg = c.surface1, bg = c.surface0 },
    BufferLineSeparatorSelected = { fg = c.surface1, bg = c.bg },
    BufferLineSeparatorVisible = { fg = c.surface1, bg = c.bg_alt },
    BufferLineTab = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineTabSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineTabSeparator = { fg = c.surface1, bg = c.surface0 },
    BufferLineTabSeparatorSelected = { fg = c.surface1, bg = c.bg },
    BufferLineTabClose = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineCloseButton = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineCloseButtonSelected = { fg = c.rose, bg = c.bg },
    BufferLineCloseButtonVisible = { fg = c.fg_muted, bg = c.bg_alt },
    BufferLinePick = { fg = c.gold, bg = c.surface0, bold = true },
    BufferLinePickSelected = { fg = c.gold, bg = c.bg, bold = true },
    BufferLinePickVisible = { fg = c.gold, bg = c.bg_alt, bold = true },
    BufferLineError = { fg = c.error, bg = c.surface0 },
    BufferLineErrorSelected = { fg = c.error, bg = c.bg },
    BufferLineErrorVisible = { fg = c.error, bg = c.bg_alt },
    BufferLineErrorDiagnostic = { fg = c.error, bg = c.surface0 },
    BufferLineErrorDiagnosticSelected = { fg = c.error, bg = c.bg },
    BufferLineWarning = { fg = c.warn, bg = c.surface0 },
    BufferLineWarningSelected = { fg = c.warn, bg = c.bg },
    BufferLineWarningDiagnostic = { fg = c.warn, bg = c.surface0 },
    BufferLineWarningDiagnosticSelected = { fg = c.warn, bg = c.bg },
    BufferLineInfo = { fg = c.info, bg = c.surface0 },
    BufferLineInfoSelected = { fg = c.info, bg = c.bg },
    BufferLineHint = { fg = c.hint, bg = c.surface0 },
    BufferLineHintSelected = { fg = c.hint, bg = c.bg },
    BufferLineNumbers = { fg = c.fg_muted, bg = c.surface0 },
    BufferLineNumbersSelected = { fg = c.fg_dim, bg = c.bg, bold = true },
    BufferLineNumbersVisible = { fg = c.fg_muted, bg = c.bg_alt },
    BufferLineGroupLabel = { fg = c.bg, bg = c.blue },
    BufferLineGroupSeparator = { fg = c.blue, bg = c.surface0 },
    BufferLineOffsetSeparator = { fg = c.surface1, bg = c.surface0 },
  }
end
return M
