local M = {}
function M.setup(c, opts)
  return {
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.fg_muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.iris, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.iris },
    CmpItemMenu = { fg = c.fg_muted },
    CmpItemKind = { fg = c.fg_dim },
    CmpItemKindClass = { fg = c.blue },
    CmpItemKindColor = { fg = c.rose },
    CmpItemKindConstant = { fg = c.teal },
    CmpItemKindConstructor = { fg = c.iris },
    CmpItemKindEnum = { fg = c.blue },
    CmpItemKindEnumMember = { fg = c.teal },
    CmpItemKindEvent = { fg = c.rose },
    CmpItemKindField = { fg = c.fg },
    CmpItemKindFile = { fg = c.fg_dim },
    CmpItemKindFolder = { fg = c.gold },
    CmpItemKindFunction = { fg = c.fg },
    CmpItemKindInterface = { fg = c.blue },
    CmpItemKindKeyword = { fg = c.fg_dim },
    CmpItemKindMethod = { fg = c.fg },
    CmpItemKindModule = { fg = c.fg_dim },
    CmpItemKindOperator = { fg = c.fg_dim },
    CmpItemKindProperty = { fg = c.fg },
    CmpItemKindReference = { fg = c.link },
    CmpItemKindSnippet = { fg = c.gold },
    CmpItemKindStruct = { fg = c.blue },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindTypeParameter = { fg = c.blue },
    CmpItemKindUnit = { fg = c.teal },
    CmpItemKindValue = { fg = c.teal },
    CmpItemKindVariable = { fg = c.fg },
    CmpDocumentation = { fg = c.fg, bg = c.bg_float },
    CmpDocumentationBorder = { fg = c.surface2, bg = c.bg_float },
  }
end
return M
