local M = {}
function M.setup(c, opts)
  return {
    DiffviewNormal = { fg = c.fg, bg = c.bg_alt },
    DiffviewCursorLine = { bg = c.bg_cursorline },
    DiffviewVertSplit = { fg = c.surface1, bg = c.bg },
    DiffviewSignColumn = { fg = c.fg_muted, bg = c.bg_alt },
    DiffviewStatusLine = { fg = c.fg_dim, bg = c.surface0 },
    DiffviewStatusLineNC = { fg = c.fg_muted, bg = c.bg_alt },
    DiffviewEndOfBuffer = { fg = c.bg_alt, bg = c.bg_alt },
    DiffviewFilePanelTitle = { fg = c.iris, bold = true },
    DiffviewFilePanelCounter = { fg = c.iris, bold = true },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewFilePanelPath = { fg = c.fg_muted },
    DiffviewFilePanelInsertions = { fg = c.git_add },
    DiffviewFilePanelDeletions = { fg = c.git_delete },
    DiffviewFilePanelRootPath = { fg = c.fg_muted },
    DiffviewFilePanelConflicts = { fg = c.error },
    DiffviewFolderName = { fg = c.blue },
    DiffviewFolderSign = { fg = c.fg_muted },
    DiffviewStatusAdded = { fg = c.git_add },
    DiffviewStatusUntracked = { fg = c.teal },
    DiffviewStatusModified = { fg = c.git_change },
    DiffviewStatusRenamed = { fg = c.git_change },
    DiffviewStatusCopied = { fg = c.teal },
    DiffviewStatusTypeChange = { fg = c.git_change },
    DiffviewStatusUnmerged = { fg = c.error },
    DiffviewStatusUnknown = { fg = c.fg_muted },
    DiffviewStatusDeleted = { fg = c.git_delete },
    DiffviewStatusBroken = { fg = c.error },
    DiffviewStatusIgnored = { fg = c.fg_muted },
    DiffviewHash = { fg = c.fg_muted },
    DiffviewReference = { fg = c.teal },
    DiffviewReflogSelectorLabel = { fg = c.blue },
    DiffviewReflogSelectorIcon = { fg = c.teal },
    DiffviewPrimary = { fg = c.blue },
    DiffviewSecondary = { fg = c.teal },
  }
end
return M
