local M = {}
function M.setup(c, opts)
  return {
    NeoTreeNormal = { fg = c.fg, bg = c.bg_alt },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg_alt },
    NeoTreeVertSplit = { fg = c.surface1, bg = c.bg_alt },
    NeoTreeWinSeparator = { fg = c.surface1, bg = c.bg_alt },
    NeoTreeEndOfBuffer = { fg = c.bg_alt, bg = c.bg_alt },
    NeoTreeRootName = { fg = c.iris, bold = true },
    NeoTreeGitAdded = { fg = c.git_add },
    NeoTreeGitConflict = { fg = c.error },
    NeoTreeGitDeleted = { fg = c.git_delete },
    NeoTreeGitIgnored = { fg = c.fg_muted },
    NeoTreeGitModified = { fg = c.git_change },
    NeoTreeGitUnstaged = { fg = c.warn },
    NeoTreeGitUntracked = { fg = c.teal },
    NeoTreeGitStaged = { fg = c.git_add },
    NeoTreeHiddenByName = { fg = c.fg_muted },
    NeoTreeIndentMarker = { fg = c.surface1 },
    NeoTreeExpander = { fg = c.surface2 },
    NeoTreeDotfile = { fg = c.fg_muted },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeFileNameOpened = { fg = c.blue },
    NeoTreeFloatBorder = { fg = c.surface2, bg = c.bg_float },
    NeoTreeFloatTitle = { fg = c.fg_dim, bg = c.bg_float, bold = true },
    NeoTreeTitleBar = { fg = c.fg_dim, bg = c.surface0, bold = true },
    NeoTreeFilterTerm = { fg = c.green, bold = true },
    NeoTreeSymbolicLinkTarget = { fg = c.teal },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeFileIcon = { fg = c.fg_dim },
    NeoTreeModified = { fg = c.warn },
    NeoTreeMessage = { fg = c.fg_muted, italic = true },
    NeoTreeDimText = { fg = c.fg_muted },
    NeoTreeTabActive = { fg = c.fg, bg = c.bg, bold = true },
    NeoTreeTabInactive = { fg = c.fg_muted, bg = c.bg_alt },
    NeoTreeTabSeparatorActive = { fg = c.surface1, bg = c.bg },
    NeoTreeTabSeparatorInactive = { fg = c.surface1, bg = c.bg_alt },
  }
end
return M
