local M = {}
function M.setup(c, opts)
  return {
    SnacksNormal = { fg = c.fg, bg = c.bg_float },
    SnacksDashboardNormal = { fg = c.fg, bg = c.bg },
    SnacksDashboardDesc = { fg = c.fg_dim },
    SnacksDashboardFile = { fg = c.blue },
    SnacksDashboardDir = { fg = c.fg_muted },
    SnacksDashboardFooter = { fg = c.fg_muted, italic = true },
    SnacksDashboardHeader = { fg = c.iris },
    SnacksDashboardIcon = { fg = c.teal },
    SnacksDashboardKey = { fg = c.gold },
    SnacksDashboardSpecial = { fg = c.iris },
    SnacksDashboardTitle = { fg = c.iris, bold = true },
    SnacksPickerBorder = { fg = c.surface2, bg = c.bg_float },
    SnacksPickerTitle = { fg = c.fg_dim, bg = c.bg_float, bold = true },
    SnacksPickerPrompt = { fg = c.iris },
    SnacksPickerSearch = { fg = c.gold },
    SnacksPickerDir = { fg = c.fg_muted },
    SnacksPickerFile = { fg = c.fg },
    SnacksPickerSelected = { fg = c.fg, bg = c.bg_visual },
    SnacksPickerMatch = { fg = c.iris, bold = true },
    SnacksIndent = { fg = c.surface1 },
    SnacksIndentScope = { fg = c.surface2 },
    SnacksNotifierBorderError = { fg = c.error },
    SnacksNotifierBorderWarn = { fg = c.warn },
    SnacksNotifierBorderInfo = { fg = c.info },
    SnacksNotifierBorderDebug = { fg = c.fg_muted },
    SnacksNotifierBorderTrace = { fg = c.iris },
    SnacksNotifierIconError = { fg = c.error },
    SnacksNotifierIconWarn = { fg = c.warn },
    SnacksNotifierIconInfo = { fg = c.info },
    SnacksNotifierIconDebug = { fg = c.fg_muted },
    SnacksNotifierIconTrace = { fg = c.iris },
    SnacksNotifierTitleError = { fg = c.error, bold = true },
    SnacksNotifierTitleWarn = { fg = c.warn, bold = true },
    SnacksNotifierTitleInfo = { fg = c.info, bold = true },
    SnacksNotifierTitleDebug = { fg = c.fg_muted, bold = true },
    SnacksNotifierTitleTrace = { fg = c.iris, bold = true },
  }
end
return M
